const carta = [
    { type: "Entrante", name: "Pan de ajo con queso", precio: 3.50, gluten: "si", crustaceos: "no", huevo: "no", pescado: "si", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Entrante", name: "Croquetas de la abuela", precio: 4.25, gluten: "si", crustaceos: "si", huevo: "si", pescado: "si", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "si", apio: "si", mostaza: "si", sesamo: "si", sulfitos: "no", moluscos: "si" },
    { type: "Entrante", name: "Lagrimitas de pollo", precio: 4.50, gluten: "si", crustaceos: "no", huevo: "si", pescado: "si", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "si", sulfitos: "no", moluscos: "no" },
    { type: "Entrante", name: "Revuelto campero(Revuelto de patatas, huevo, pimiento, cebolla, chorizo y champiñones", precio: 5.25, gluten: "si", crustaceos: "no", huevo: "si", pescado: "si", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Entrante", name: "Foie de pato", precio: 6.25, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Entrante", name: "Patatas fritas con salsa a elegir", precio: 4.40, gluten: "si", crustaceos: "no", huevo: "si", pescado: "si", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Entrante", name: "Patatas gratinadas(Patatas con bacon, bechamel y queso fundido)", precio: 7.25, gluten: "si", crustaceos: "no", huevo: "si", pescado: "si", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Entrante", name: "Alitas de pollo", precio: 4.50, gluten: "si", crustaceos: "no", huevo: "no", pescado: "si", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Entrante", name: "Nachos", precio: 5.95, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Entrante", name: "Ensalada a los 3 quesos(Lechuga, tomate, cebolla, pavo, queso fresco, queso cheddar y rulo de cabra)", precio: 9.25, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Entrante", name: "Ensalada mixta(Lechuga, tomate y cebolla)", precio: 4.95, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Entrante", name: "Ensalada césar(Lechuga, tomate, aceitunas negras, pavo, queso fresco, huevo duro, finger de pollo, picatoste y salsakebab o césar a elegir)", precio: 9.25, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "si", sesamo: "si", sulfitos: "si", moluscos: "no" },
    { type: "Plato", name: "Tallarines bolognesa", precio: 7.95, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "si", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Tortellini de ricotta con espinacas carbonara", precio: 7.95, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Macarrones sicilianos(Salsa bechamel, nata, ternera salteada, bacon y tomate)", precio: 7.95, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Pizza carbonara(Tomate, queso, bacon y salsa carbonara)", precio: 10.25, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Pizza margarita(Tomate y queso)", precio: 8.50, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Pizza americana(Tomate, queso, bacon, ternera y aceitunas negras)", precio: 10.95, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "si", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Pizza Juanito(Tomate, queso, carne mechá y queso viejo)", precio: 10.95, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "si", sulfitos: "si", moluscos: "no" },
    { type: "Plato", name: "Pizza suprema(Tomate, queso, pollo, pimiento verde y jamón de york)", precio: 11.50, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "si", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Pizza barbacoa(Tomate, queso, ternera, pimiento verde, jamon de york y barbacoa)", precio: 11.50, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "si", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Pizza cuatro quesos(Tomate, mozzarella, roquefort, cheddar y parmesano)", precio: 10.75, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "si", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Pizza furiosa(Tomate, queso, ternera, pepperoni y salsa chili)", precio: 11.50, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "si", mostaza: "si", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Pizza funghi(Tomate, queso, champiñones, funghi porcini y bechamel)", precio: 12.50, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "si", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Pizza del norte(Tomate, eddam, salmon ahumado, queso fresco, anchoas y aceitunas)", precio: 11.50, gluten: "si", crustaceos: "no", huevo: "no", pescado: "si", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Burguer Jack Daniels(Carne vacuno 225g, salsa Jack Daniels, mezclum, queso cheddar, bacon, tomate, queso edam y patatas clásicas)", precio: 9.95, gluten: "si", crustaceos: "no", huevo: "si", pescado: "si", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "si", apio: "no", mostaza: "si", sesamo: "si", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Burguer New York(Carne novillo 200g con pepinillo, cebolla frita, bacon, queso manchego, huevo frito y salsa a las 3 pimientas)", precio: 9.50, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "si", mostaza: "si", sesamo: "no", sulfitos: "si", moluscos: "no" },
    { type: "Plato", name: "Burguer Angus(Carne buey Angus 180g, lechuga, tomate, cebolla frita, cheddar, bacon, patatas clásicas y salsa Juanito)", precio: 9.75, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "si", mostaza: "no", sesamo: "no", sulfitos: "si", moluscos: "no" },
    { type: "Plato", name: "Burguer iberica(Carne vacuno 225g, jamon iberico y queso viejo)", precio: 9.75, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Burguer texmex(Carne vacuno 225g, guacamole, cebolla crujiente, bacon, tomate y queso cheddar)", precio: 9.50, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "si", mostaza: "no", sesamo: "no", sulfitos: "si", moluscos: "no" },
    { type: "Plato", name: "Burguer retinta(Carne retinta 225g, edam, cheddar, bacon, huevo plancha y salsa gaucha)", precio: 9.95, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "si", sulfitos: "si", moluscos: "no" },
    { type: "Plato", name: "Burguer royal(Carne novillo retinto 200g, bacon, pepinillo, rulo de cabra, cebolla caramelizada al Pedro Ximenez con salsa mostaza y miel)", precio: 9.25, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "si", mostaza: "no", sesamo: "no", sulfitos: "si", moluscos: "no" },
    { type: "Plato", name: "Burguer Crispy(Pechuga de pollo rebozada, queso, jamon de york, lechuga, tomate y mahonesa)", precio: 5.25, gluten: "si", crustaceos: "no", huevo: "si", pescado: "si", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "si", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Burguer Juanito(Pan brioche, triple carne de ternera 110g, salsa cheddar, edam, bacon, doble queso cheddar fundido y 3 aritos de cebolla)", precio: 11.95, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "si", apio: "no", mostaza: "no", sesamo: "si", sulfitos: "si", moluscos: "si" },
    { type: "Plato", name: "Wok oriental(Salteado de pollo con verduras al wok)", precio: 8.50, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Se bueno(Filete de pollo con tomate, lechuga, cebolla y zanahoria)", precio: 5.95, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Pizza York(Tomate, mozzarella, jamon york y orégano)", precio: 9.50, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Pizza vegetal(Tomate, tomate sherry, mozzarella, queso edam y albahaca)", precio: 9.50, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Pizza salami(Tomate, mozzarella, salami y orégano)", precio: 9.50, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Lasagna sin gluten", precio: 9.50, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Serranito vegetal(Lechuga, tomate, huevo duro y mahonesa)", precio: 4.20, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Serranito peleon(Lomo de cerdo, queso, bacon, tomate y mojo picon)", precio: 5.50, gluten: "si", crustaceos: "no", huevo: "si", pescado: "si", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "si", moluscos: "si" },
    { type: "Plato", name: "Serranito roquefort(Lomo de cerdo, bacon y roquefort)", precio: 5.50, gluten: "si", crustaceos: "no", huevo: "si", pescado: "si", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Serranito guachon(Lomo de cerdo, queso, pimiento frito y salsa gaucha)", precio: 6.25, gluten: "si", crustaceos: "no", huevo: "si", pescado: "si", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "si", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Plato", name: "Serranito Juanito(Pechuga de pollo plancha, jamon, bacon, tortilla francesa, tomate, pimiento frito y salsa Juanito)", precio: 6.95, gluten: "si", crustaceos: "no", huevo: "si", pescado: "si", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Tercio Cruzcampo 33cl", precio: 1.25, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Tercio Cruzcampo especial", precio: 2.50, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Cruzcampo sin gluten", precio: 2.50, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Pinta Paulaner", precio: 4.00, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Tercio Desperados", precio: 3.00, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Tercio artesana IPA, Ape Pale y Trigo", precio: 2.50, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Tinto verano", precio: 1.50, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Tercio Ladrón de Manzanas", precio: 2.50, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Cerveza en jarra de 68cl", precio: 2.50, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Refrescos 35cl", precio: 1.80, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Refrescos jarra 68cl", precio: 3.30, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Zumos 20cl", precio: 1.50, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Agua 50cl", precio: 1.20, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Agua 1l", precio: 2.15, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "no", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Agua con gas", precio: 1.50, gluten: "no", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "no", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Bebida", name: "Café", precio: 1.50, gluten: "si", crustaceos: "no", huevo: "no", pescado: "no", cacahuetes: "no", soja: "si", lacteos: "si", frutoscascara: "no", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "si", moluscos: "no" },
    { type: "Postre", name: "JuanitoShake(Batido helado con sirope y sabor a elegir; Con nata por +0.50€)", precio: 4.95, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "si", soja: "si", lacteos: "si", frutoscascara: "si", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Postre", name: "Coulant de chocolate(Delicioso con chocolate caliente, helado y sirope a elegir)", precio: 4.95, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "si", soja: "si", lacteos: "si", frutoscascara: "si", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Postre", name: "Crepe veneciano(Relleno de 3 bolas de helado a elegir, con nata y sirope a elegir)", precio: 6.25, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "si", soja: "si", lacteos: "si", frutoscascara: "si", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Postre", name: "Crepe frances(Relleno de 3 bolas de helado a elegir, cobertura de nutella y chocolate blanco)", precio: 6.50, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "si", soja: "si", lacteos: "si", frutoscascara: "si", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
    { type: "Postre", name: "Huevo de Juanito(Brownie servido en copa con nata, 2 bolas de helado y sirope a elegir, y corteza)", precio: 6.95, gluten: "si", crustaceos: "no", huevo: "si", pescado: "no", cacahuetes: "si", soja: "si", lacteos: "si", frutoscascara: "si", apio: "no", mostaza: "no", sesamo: "no", sulfitos: "no", moluscos: "no" },
];

showMenu();

function showMenu() {
    const typeSection = document.getElementById('type-section');
    let type = '';
    let table = '';
    let cont = 1;
    carta.forEach(dish => {
        if (!(type === dish.type)) {
            type = dish.type;
            let typeTitle = document.createElement('H2');
            typeTitle.textContent = type;
            typeSection.appendChild(typeTitle);
            table = document.createElement('TABLE');
            typeSection.appendChild(table);
        }
        let row = document.createElement('TR');
        row.setAttribute('id', cont);
        table.appendChild(row);
        let rowDish = document.getElementById(cont);
        let dishName = document.createElement('TD');
        dishName.textContent = dish.name;
        let dishPrize = document.createElement('TD');
        dishPrize.textContent = dish.precio+'€';
        rowDish.appendChild(dishName);
        rowDish.appendChild(dishPrize);
        cont++;
    });
    
} 